[32mINFO    [0m root:test_redirect_callback_url.py:17 Inside test_redirect_callback_url function
[32mINFO    [0m root:requestsUtility.py:30 URL used for test is https://web-aqa-05.talech.com/sso/callback?code=98765432099876543209987654
[32mINFO    [0m root:requestsUtility.py:32 Status code: 422
[32mINFO    [0m root:requestsUtility.py:49 Expected status code: 422 and actual status code: 422 
[32mINFO    [0m root:test_redirect_callback_url.py:24 After test_redirect_callback_url function